### ISSUE TITLE
a simplified guide to Orcid verification

### ISSUE THREAD

**Issue by 1nbar** [ecoevo-social/ecoevo.social-docs#35]
someone asked for it in ecoevo.social's #FediHelp tag: https://ecoevo.social/@Gentle/109326868109071613
not sure how clear my explanation is as ESL who's from another mastodon instance and (as non-academic) does not have ORCiD account.

**Comment by alxsimon** [comment]
Thanks for the issue, a guide on verifying accounts is indeed needed.

**Comment by alxsimon** [comment]
ORCID issue https://github.com/ORCID/ORCID-Source/issues/6668

**Comment by alxsimon** [comment]
Won't be supported for a while, cf. above issue
